#!/bin/bash
###
# mtwComposer
#
# @version $Id:
# @package mtwComposer
# @copyright Copyright (C) 2004 - 2016 Matware. All rights reserved.
# @author Matias Aguirre
# @email maguirre@matware.com.ar
# @link http://www.matware.com.ar/
# @license GNU General Public License version 2 or later; see LICENSE
#

PROJECT="mtwcomposer"
VERSION="1.0.0"

RELEASE_DIR=`pwd`
PKG_DIR="pkg_$PROJECT"

COM_PACKAGE="com_mtwcomposer"

# copy all needed files
rm *.zip
#rm -rf $DIR

mkdir ${PKG_DIR}

cp -r ../administrator/components/com_mtwcomposer ${PKG_DIR}/com_mtwcomposer
cp -r ../media ${PKG_DIR}/com_mtwcomposer/.
cp -r ../media ${PKG_DIR}/.

# Zip mtwComposer component
cd ${PKG_DIR}/${COM_PACKAGE}
zip -rq ${COM_PACKAGE}-${VERSION}.zip .
mv ${COM_PACKAGE}-${VERSION}.zip ${RELEASE_DIR}/.
cd ${RELEASE_DIR}

# create symlink
#rm -rf com_${PROJECT}-latest.zip
#ln -s $PACKAGE com_${PROJECT}-latest.zip

# Cleanup
rm -rf ${PKG_DIR}
#rm packages/*.zip
